# Generated by Django 3.2 on 2021-06-20 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_stock_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='slug',
        ),
    ]
