# Generated by Django 3.2 on 2021-07-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_stock_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSetLoading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('loaded_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.FileField(upload_to='uploads/')),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
