# Generated by Django 3.2 on 2021-08-29 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_stock_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ('product', 'size')},
        ),
    ]
