version: '3'

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - static_volume:/home/backend/web/static
      - media_volume:/home/backend/web/media
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=petmik
      - POSTGRES_PASSWORD=reimatec
      - POSTGRES_DB=superzero_db
  vue:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    volumes:
      - vue_dist:/app/dist
    depends_on:
      - web
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/backend/web/static
      - media_volume:/home/backend/web/media
      - vue_dist:/app/dist
    ports:
      - 80:80
    depends_on:
      - web
      - vue

volumes:
  static_volume:
  media_volume:
  vue_dist:
  postgres_data:
