# Generated by Django 3.2 on 2021-06-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создан'), ('PREPARED', 'Собран'), ('ON THE WAY', 'В пути'), ('COMPLETED', 'Доставлен'), ('CANCELLED', 'Отменен')], default='CREATED', max_length=64),
        ),
    ]
