# Generated by Django 3.2 on 2021-06-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
