# Generated by Django 3.2.2 on 2022-01-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('type', models.CharField(choices=[('Off line', 'Off line'), ('On line', 'On line'), ('mixed', 'mixed')], max_length=16)),
                ('slug', models.SlugField()),
                ('logo_image', models.ImageField(upload_to='brands')),
                ('main_image', models.ImageField(upload_to='brands')),
                ('short_info', models.CharField(max_length=255)),
                ('detailed_info', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
