# Generated by Django 3.2 on 2021-05-03 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('color', models.CharField(max_length=64)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, null=True)),
                ('basic_price', models.PositiveIntegerField(blank=True, null=True)),
                ('sizes_scale', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.brand')),
            ],
            options={
                'ordering': ('-date_added',),
                'unique_together': {('name', 'color')},
            },
        ),
    ]
