# Generated by Django 3.2 on 2021-05-05 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210505_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='main_image',
            new_name='image',
        ),
    ]
