# Generated by Django 3.2 on 2021-07-14 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_image_imagelibrary_imagesetloading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesetloading',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.imagelibrary'),
        ),
        migrations.CreateModel(
            name='ProductSetLoading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('loaded_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.FileField(upload_to='uploads/')),
                ('completed', models.BooleanField(default=False)),
                ('images_library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.imagelibrary')),
            ],
        ),
    ]
