# Generated by Django 3.2 on 2021-07-14 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20210714_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsetloading',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.action'),
        ),
    ]
