# Generated by Django 3.2 on 2021-07-16 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_productsetloading_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
    ]
