# Generated by Django 3.2 on 2021-07-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20210716_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
