# Generated by Django 3.2 on 2021-09-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_action_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alt',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
