# Generated by Django 3.2 on 2021-09-10 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_actions', to='product.brand'),
        ),
    ]
