# Generated by Django 3.2 on 2021-08-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_profile_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bonuses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
