# Generated by Django 3.2 on 2021-08-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_profile_bonuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_bonus', models.PositiveIntegerField(choices=[(100, 100), (200, 200), (300, 300)], unique=True, verbose_name='Initial bonus')),
            ],
            options={
                'verbose_name': 'bonus settings',
                'verbose_name_plural': 'bonus settings',
            },
        ),
    ]
