# Generated by Django 3.2 on 2021-08-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_bonussettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonussettings',
            name='initial_bonus',
            field=models.PositiveIntegerField(choices=[(100, '100'), (200, '200'), (300, '300')], unique=True, verbose_name='Initial bonus'),
        ),
    ]
